### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mysterio0801**
Lo dekh lo bsdk @stygian-96

### CODE REVIEW

**Comment by stygian-96** [comment]
> Lo dekh lo bsdk @stygian-96

Hatt murgi ke lund @mysterio0801

**Comment by mysterio0801** [comment]
Muh me loge bsdk

**Comment by stygian-96** [comment]
> Muh me loge bsdk

Chalo niklo betichod

**Comment by stygian-96** [comment]
> Muh me loge bsdk 🐓

**Comment by mysterio0801** [comment]
Gaand marao bakrichod..☝👆

**Comment by stygian-96** [comment]
🤲.......👐

**Comment by stygian-96** [comment]
> Check it out bruh @stygian-96

Respected gentleman, i checked it out and i found it really useful

**Pull request merged**
